package constants

type ERROR_CODE string
type ERROR_MSG error

const (
	// Version
	VERSION      = "1.0"
	VERSION_NAME = "Inbox Marketing"

	AUTH_SIGNED_KEY  = "PitelSecretKey"
	DEFAULT_PASSWORD = "Default@!#PORTAL"

	// forbidden
	ERR_UNAUTHORIZED             ERROR_CODE = "ERR_UNAUTHORIZED"
	ERR_FORBIDDEN                ERROR_CODE = "ERR_FORBIDDEN"
	ERR_SERVICE_UNAVAILABLE      ERROR_CODE = "ERR_SERVICE_UNAVAILABLE"
	ERR_INTERNAL_SERVER_ERROR    ERROR_CODE = "ERR_INTERNAL_SERVER_ERROR"
	ERR_NOT_IMPLEMENTED          ERROR_CODE = "ERR_NOT_IMPLEMENTED"
	ERR_NOT_IMPLEMENT_FOR_MASTER ERROR_CODE = "ERR_NOT_IMPLEMENT_FOR_MASTER"
	ERR_DB_CONNECTION_ERROR      ERROR_CODE = "ERR_DB_CONNECTION_ERROR"

	// token
	ERR_TOKEN_IS_EMPTY   ERROR_CODE = "ERR_TOKEN_IS_EMPTY"
	ERR_TOKEN_IS_INVALID ERROR_CODE = "ERR_TOKEN_IS_INVALID"
	ERR_TOKEN_IS_EXPIRED ERROR_CODE = "ERR_TOKEN_IS_EXPIRED"

	ERR_REFRESH_TOKEN_INVALID ERROR_CODE = "ERR_REFRESH_TOKEN_INVALID"

	// user
	ERR_USERNAME_EXISTS           ERROR_CODE = "ERR_USERNAME_EXISTS"
	ERR_USERNAME_NOT_FOUND        ERROR_CODE = "ERR_USERNAME_NOT_FOUND"
	ERR_USER_NOTFOUND             ERROR_CODE = "ERR_USER_NOTFOUND"
	ERR_EMAIL_NOTFOUND            ERROR_CODE = "ERR_EMAIL_NOTFOUND"
	ERR_INVALID_USERNAME_PASSWORD ERROR_CODE = "ERR_INVALID_USERNAME_PASSWORD"
	ERR_MISSING_USER_ID           ERROR_CODE = "ERR_MISSING_USER_ID"
	ERR_CURRENT_PASSWORD_INVALID  ERROR_CODE = "ERR_CURRENT_PASSWORD_INVALID"
	ERR_PASSWORD_INVALID          ERROR_CODE = "ERR_PASSWORD_INVALID"
	ERR_USERNAME_IS_EXISTED       ERROR_CODE = "ERR_USERNAME_IS_EXISTED"
	ERR_USER_CODE_IS_EXISTED      ERROR_CODE = "ERR_USER_CODE_IS_EXISTED"
	ERR_USER_CODE_IS_INVALID      ERROR_CODE = "ERR_USER_CODE_IS_INVALID"

	// role
	ERR_ROLE_NOTFOUND ERROR_CODE = "ERR_ROLE_NOTFOUND"

	// business unit
	ERR_BUSINESS_UNIT_NOTFOUND ERROR_CODE = "ERR_BUSINESS_UNIT_NOTFOUND"

	// group
	ERR_GROUP_CODE_IS_EXISTED ERROR_CODE = "ERR_GROUP_CODE_IS_EXISTED"
	ERR_GROUP_NOTFOUND        ERROR_CODE = "ERR_GROUP_NOTFOUND"
	ERR_PARENT_GROUP_NOTFOUND ERROR_CODE = "ERR_PARENT_GROUP_NOTFOUND"

	// service
	ERR_SERVICE_NOTFOUND      ERROR_CODE = "ERR_SERVICE_NOTFOUND"
	ERR_USER_SERVICE_NOTFOUND ERROR_CODE = "ERR_USER_SERVICE_NOTFOUND"

	// tenant
	ERR_TENANT_NOTFOUND ERROR_CODE = "ERR_TENANT_NOTFOUND"

	// feature
	ERR_FEATURE_NOTFOUND ERROR_CODE = "ERR_FEATURE_NOTFOUND"
	ERR_FEATURE_EXIST    ERROR_CODE = "ERR_FEATURE_EXIST"

	ERR_PARAMETER_NOTFOUND ERROR_CODE = "ERR_PARAMETER_NOTFOUND"
	ERR_PARAMETER_EXIST    ERROR_CODE = "ERR_PARAMETER_EXIST"

	// request
	ERR_REQUEST_INVALID         ERROR_CODE = "ERR_REQUEST_INVALID"
	ERR_REQUEST_IS_EXISTED      ERROR_CODE = "ERR_REQUEST_IS_EXISTED"
	ERR_REQUEST_NOTFOUND        ERROR_CODE = "ERR_REQUEST_NOTFOUND"
	ERR_REQUEST_IS_EXPIRED      ERROR_CODE = "ERR_REQUEST_IS_EXPIRED"
	ERR_REQUEST_CODE_IS_INVALID ERROR_CODE = "ERR_REQUEST_CODE_IS_INVALID"

	STATE_REQUEST      string = "request"
	STATE_VERIFY_TOKEN string = "verify_token"
	STATE_VERIFY_CODE  string = "verify_code"
	STATE_SUBMIT       string = "submit"

	SUPERADMIN string = "superadmin"
	ADMIN      string = "admin"
	USER       string = "user"
)
