name: Commit Notification

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{secrets.TELEGRAM_TOKEN}}
          format: markdown
          message: |
            *Repository:*
            ${{ github.repository }} [link](https://github.com/${{ github.repository }})
            *Branch:*
            ${{ github.ref_name }}
            *Actor:*
            ${{ github.actor }}
            *Commit:*
            https://github.com/${{ github.repository }}/commit/${{github.sha}}
            *Message:*
            Action: ${{ github.event_name }} - Commit: ${{ github.event.commits[0].message }}
